//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockLinkedView1
    {
        public string Expr1 { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<bool> StreetCalcs { get; set; }
        public Nullable<bool> ConcreteCalcs { get; set; }
        public Nullable<bool> Geometry { get; set; }
        public Nullable<bool> MXD_Export { get; set; }
        public Nullable<bool> Photoline_MXD_Export { get; set; }
        public Nullable<bool> CIC_Summary_Sheet_Export { get; set; }
        public Nullable<bool> Streets_Sketchline_Edits { get; set; }
        public Nullable<bool> Concrete_Edits { get; set; }
        public Nullable<bool> MXD_PDF { get; set; }
        public Nullable<bool> Photoline_PDF { get; set; }
        public Nullable<bool> Photolog_PDF { get; set; }
        public Nullable<bool> FTP_Upload { get; set; }
        public Nullable<System.DateTime> Submitted { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public string PageNo { get; set; }
        public System.Guid GlobalID { get; set; }
        public Nullable<System.DateTime> ReviewByDate { get; set; }
        public string ReviewBy { get; set; }
        public string CalcBy { get; set; }
        public Nullable<System.DateTime> CalcByDate { get; set; }
        public string SurveyBy { get; set; }
        public Nullable<System.DateTime> SurveyByDate { get; set; }
        public string strCCEProjectNumber { get; set; }
        public Nullable<int> BlockNo { get; set; }
        public string Notes { get; set; }
        public string testYN { get; set; }
    }
}
